language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
matrix:
  allow_failures:
    - python: '2.6'
install:
- pip install flake8
script:
- flake8 . --max-complexity 5 --max-line-length 99 --ignore E201,E202,E402
- python -m doctest README.md
- python setup.py test
notifications:
  email: false