language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
matrix:
  allow_failures:
    - python: '2.6'
    - python: '2.7'
    - python: 'pypy'
    - python: '3.6'
install:
- pip install flake8
script:
- flake8 . --max-complexity 6 --max-line-length 99 --ignore E201,E202,E402
- python -m doctest README.md
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: jwg
  password:
    secure: fGJvlfrCDGz0gSHc0EJRyuh3QsvBbbQlZ4YWOoW8da2FZXnPpSZCTugpxE2Ssomlt+GtDB8irQl4e5LQZeWsJb2F2XAcKJcL3guFe5eGBUsVn6+xayW7X6c7K6xadxJfE/lmDYGx+v91PlQl9PkyDBigUD9VpT66GXAUMFRB4pFoEiOHXVaCaLvP+Rv9+4wZnRzpMMbP6PPDeWnoUG818FMOKDX2MIojWmII0UIQCDb3CLARFDKIk1zJH5bmJOMkvedpGaRm9LGmpaTM3O7KVPPWlKxiykfvc5sa4aGvpK1h/0F6r4KHeHsozZk9ZmETB3mpTu2TKJGejBf+ffpYMuXGcg0hCHqHk9PLfkAbP+e4fZ1LbBwc9H2P7gTlYa7VLAFSffQcwBahqEPJxcPYOnYWmRfif0wtaVHtqUecSLXqLdZTe+rWhdj+PNftrf2vcKRBBjdIgw1woOZb1E6N+FnYYi++yF2letHITrLev/6kUJwWKIXinxLsln80Dz2hYxHj6+IWLpQs9G6wzuBr+X9P643OBgoqSTe2vw5V6plsbZLnsekJQH54EYiFx1QK2vEXFmYH5Izh8UqOq3TuyECp7uT6jzgGEmukin1S0fEiOEI+5kN1Oz2CgjGyk8WRxXY/fMkrwQ/G95hWfBur9kMYJ2vRDXio1bCHyK3k9Rg=
  on:
    tags: true
